// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRandomSubdirPath():Promise<string>;

export function LoadsSubdirs():Promise<void>;

export function OpenWinner():Promise<string>;

export function ResetFolder():Promise<void>;

export function SetFolder():Promise<string>;
