// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRandomSubdirPath() {
  return window['go']['main']['App']['GetRandomSubdirPath']();
}

export function LoadsSubdirs() {
  return window['go']['main']['App']['LoadsSubdirs']();
}

export function OpenWinner() {
  return window['go']['main']['App']['OpenWinner']();
}

export function ResetFolder() {
  return window['go']['main']['App']['ResetFolder']();
}

export function SetFolder() {
  return window['go']['main']['App']['SetFolder']();
}
